# TODO: Add Grafana and Prometheus

services:
  postgres:
    image: postgres:18
    ports:
      - "5434:5432" # Avoid port clash with host machine postgres instance
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=it_support_platform
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app-network

  localstack:
    image: localstack/localstack
    ports:
      - "4567:4566" # Avoid port clash with host machine localstack instance
    environment:
      - SERVICES=sqs,s3
      - EDGE_PORT=4566
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  localstack_data:
