spring:
  application:
    name: worker

  datasource:
    url: jdbc:postgresql://localhost:5434/it_support_platform
    username: postgres
    password: postgres

aws:
  region: eu-west-2
  access-key: test
  secret-key: test
  sqs:
    endpoint: http://localhost:4567
    queue-name: incident-workflow

worker:
  sqs:
    maxMessages: 10
    waitSeconds: 10
    visibilityTimeoutSeconds: 30
  llm:
    ollama:
      baseUrl: http://localhost:11434
      model: llama3.1:8b
